# Generated by Django 3.1.1 on 2020-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20200908_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
